<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Login</name>
   <tag></tag>
   <elementGuidId>6a279823-c898-4807-9a75-85d5c8b71e2d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='submit'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e4271d99-f2f5-4781-a137-c6bfaf7c1164</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>5a778843-f8db-420a-9b13-e7875938799d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>inline-block shrink-0 rounded-md border px-12 py-3 text-sm font-medium text-sweed-color-light bg-transparent transition hover:bg-sweed-color-light hover:text-sweed-gray focus:outline-none active:text-sweed-color-light</value>
      <webElementGuid>bdc927e1-cc2f-4b5e-9719-a15edef0b2b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                  Login
                </value>
      <webElementGuid>2802a97a-53f9-48a6-91a7-8558c833bfff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;dark&quot;]/body[@class=&quot;bg-sweed-gray&quot;]/section[@class=&quot;bg-sweed-gray&quot;]/div[@class=&quot;lg:grid lg:min-h-screen lg:grid-cols-12&quot;]/main[@class=&quot;flex items-center justify-center px-8 py-8 sm:px-12 lg:col-span-7 lg:py-12 lg:px-16 xl:col-span-6&quot;]/div[@class=&quot;max-w-xl lg:max-w-3xl&quot;]/form[2]/div[@class=&quot;col-span-6 sm:flex sm:items-center sm:gap-4 mt-8&quot;]/button[@class=&quot;inline-block shrink-0 rounded-md border px-12 py-3 text-sm font-medium text-sweed-color-light bg-transparent transition hover:bg-sweed-color-light hover:text-sweed-gray focus:outline-none active:text-sweed-color-light&quot;]</value>
      <webElementGuid>5179df4b-e483-45f7-84a9-e7e985bd40c3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='submit'])[2]</value>
      <webElementGuid>0ce1d956-63e7-487a-998b-a758b8e60a24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Password'])[1]/following::button[1]</value>
      <webElementGuid>34271a56-6b8b-4f89-840d-c567e17d6ddc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email'])[1]/following::button[1]</value>
      <webElementGuid>8dccf84f-7b21-4f2b-ac2d-728e95849191</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Login']/parent::*</value>
      <webElementGuid>3ed12f97-7412-4fe8-ac26-5a9b85bc5fc8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/button</value>
      <webElementGuid>b2a4dc88-bb31-4e0b-815a-36b77c8b53c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = '
                  Login
                ' or . = '
                  Login
                ')]</value>
      <webElementGuid>d3e90982-f2a8-4071-9ff3-f3a57ae0521e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
