<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>dd_Total</name>
   <tag></tag>
   <elementGuidId>7b880e64-a027-46a0-b3ef-4b0db974de58</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Subtotal'])[1]/following::dd[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>dd</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>dd</value>
      <webElementGuid>4382e03f-a2e8-413a-9f6c-7271547fd7ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>฿32</value>
      <webElementGuid>58dedb8a-9fb6-4b4a-a118-82b9b46d865a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;dark&quot;]/body[@class=&quot;bg-sweed-dark text-sweed-white&quot;]/section[@class=&quot;lg:w-[70%] w-[80%] mx-auto&quot;]/div[@class=&quot;mx-auto max-w-screen-xl py-8 sm:py-12 lg:px-8&quot;]/div[@class=&quot;mx-auto max-w-3xl&quot;]/div[@class=&quot;mt-4 bg-sweed-gray p-4 rounded-lg text-sweed-white&quot;]/div[@class=&quot;mt-8 flex justify-end border-t border-gray-100 pt-8&quot;]/div[@class=&quot;w-screen max-w-lg space-y-4&quot;]/dl[@class=&quot;space-y-0.5&quot;]/div[@class=&quot;flex justify-between&quot;]/dd[1]</value>
      <webElementGuid>138c4b8c-ebc6-45d2-9ccf-e2209ca54927</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Subtotal'])[1]/following::dd[1]</value>
      <webElementGuid>cc977966-4960-4648-9150-f47f84637fe9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='฿20'])[1]/following::dd[1]</value>
      <webElementGuid>4f0bcd7b-155c-4f07-94ab-48db7744f748</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='VAT'])[1]/preceding::dd[1]</value>
      <webElementGuid>137aac50-a4ba-410c-b64c-b39612097ca1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='฿3'])[1]/preceding::dd[1]</value>
      <webElementGuid>895fc4e7-7cd6-4535-a6e3-836e27894f6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='฿32']/parent::*</value>
      <webElementGuid>8a1737e7-86c4-4917-83aa-518273c39289</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//dd</value>
      <webElementGuid>25ff8c12-d8f6-4300-a445-074c745795df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//dd[(text() = '฿32' or . = '฿32')]</value>
      <webElementGuid>08efe0d8-6524-4223-9652-75eaccacf224</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
