<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Price2</name>
   <tag></tag>
   <elementGuidId>02bd2a7d-1eb3-46b3-acdb-6d74fcce0891</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='again'])[1]/following::span[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.flex.flex-1.items-center.justify-end.gap-2 > span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>e5c70de3-3a9e-43a6-81cb-eb49f5b47d08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>฿2</value>
      <webElementGuid>7ef248e1-1ad2-49e7-a4fd-21d878ac68d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;dark&quot;]/body[@class=&quot;bg-sweed-dark text-sweed-white&quot;]/section[@class=&quot;lg:w-[70%] w-[80%] mx-auto&quot;]/div[@class=&quot;mx-auto max-w-screen-xl py-8 sm:py-12 lg:px-8&quot;]/div[@class=&quot;mx-auto max-w-3xl&quot;]/div[@class=&quot;mt-4 bg-sweed-gray p-4 rounded-lg text-sweed-white&quot;]/ul[@class=&quot;space-y-4&quot;]/li[@class=&quot;flex items-center gap-4&quot;]/div[@class=&quot;flex flex-1 items-center justify-end gap-2&quot;]/span[1]</value>
      <webElementGuid>407d179f-350e-4e7e-9d56-09de3ae05bc7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='again'])[1]/following::span[1]</value>
      <webElementGuid>2e293d1e-eaca-460f-b37d-5c613328b4c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='+'])[1]/following::span[1]</value>
      <webElementGuid>2468dd88-8ce1-46ce-a25a-813a59857c88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Quantity'])[2]/preceding::span[1]</value>
      <webElementGuid>942530c9-274e-435a-8b71-c311a7abe1e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='−'])[2]/preceding::span[1]</value>
      <webElementGuid>ae9de817-111d-4f22-a697-9c3aae09aee4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='฿2']/parent::*</value>
      <webElementGuid>192f9e0b-5c25-43cd-9565-9378d8bd1d28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/span</value>
      <webElementGuid>c8c740fa-1b03-4146-891d-e6e644d8d9bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '฿2' or . = '฿2')]</value>
      <webElementGuid>25021046-f8a7-490c-976b-4dd1eb741012</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
