<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Price1</name>
   <tag></tag>
   <elementGuidId>e60bbf88-57d2-49cb-9005-d9dd904f776b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='first'])[1]/following::span[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.flex.flex-1.items-center.justify-end.gap-2 > span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>0f987845-80c8-4663-a826-7d2f045a5d9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>฿2</value>
      <webElementGuid>51d39a0e-09c4-495d-99db-8c4598f692a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;dark&quot;]/body[@class=&quot;bg-sweed-dark text-sweed-white&quot;]/section[@class=&quot;lg:w-[70%] w-[80%] mx-auto&quot;]/div[@class=&quot;mx-auto max-w-screen-xl py-8 sm:py-12 lg:px-8&quot;]/div[@class=&quot;mx-auto max-w-3xl&quot;]/div[@class=&quot;mt-4 bg-sweed-gray p-4 rounded-lg text-sweed-white&quot;]/ul[@class=&quot;space-y-4&quot;]/li[@class=&quot;flex items-center gap-4&quot;]/div[@class=&quot;flex flex-1 items-center justify-end gap-2&quot;]/span[1]</value>
      <webElementGuid>5c944729-6ddd-436a-9369-287c7a0d750f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='again'])[1]/following::span[1]</value>
      <webElementGuid>625ffde2-f336-4a48-94cf-378c17e3c385</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='+'])[1]/following::span[1]</value>
      <webElementGuid>8a3b4abc-a632-4e14-a9f9-995652f856bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Quantity'])[2]/preceding::span[1]</value>
      <webElementGuid>e14c740c-8c21-4573-ac8d-364faa0136f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='−'])[2]/preceding::span[1]</value>
      <webElementGuid>6afacce4-3b19-48d8-b9a4-83700dd0fc1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='฿2']/parent::*</value>
      <webElementGuid>957ecab5-e5c8-40a2-ad98-7776efeb7eef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/span</value>
      <webElementGuid>fb7cd824-a02b-4644-8c7e-546cc837bff8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '฿2' or . = '฿2')]</value>
      <webElementGuid>4e45d765-d516-4e73-9ea5-803305282ddf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
